#ifndef C_TESTS_CONFIG_H
#define C_TESTS_CONFIG_H

#define ERROR_MESSAGE_MAX_LEN 256
#define GROUP_TEST_NAME_MAX_LEN 80
#define TEST_NAME_MAX_LEN 80

#define TEST_SUCCESS 0
#define TEST_ERROR 1

#endif  // C_TESTS_CONFIG_H