#ifndef C_TESTS_CONFIG_H
#define C_TESTS_CONFIG_H

#define ERROR_MESSAGE_MAX_LEN 256
#define GROUP_TEST_NAME_MAX_LEN 80
#define TEST_NAME_MAX_LEN 80

#define TEST_SUCCESS 0
#define TEST_ERROR 1

#define PRINT_RED "\033[0;31m"
#define PRINT_GREEN "\033[0;32m"
#define PRINT_DEFAULT "\033[0m"

#endif  // C_TESTS_CONFIG_H